/**
 * Mise toolchain model, renderer, preview, and legacy Aftman migration policy.
 *
 * Generated toolchain state is deterministic, flavor-aware, and contains no
 * Aftman references (AC-01). A legacy `aftman.toml` is previewed as a mise
 * equivalent and left untouched unless the developer explicitly removes it
 * (EC-07). The mise binary itself is never required to *render* toolchain
 * state — only to install it (see ./mise-adapter.ts).
 */

import type { InitFlavor } from "../commands/init";

/** Project-local generated toolchain config path. */
export const MISE_CONFIG_PATH = "mise.toml";

/** Stable prompt IDs for the toolchain preview/confirm UI. */
export const PREVIEW_ID = "mise__preview";
export const CONFIRM_ID = "mise__confirm";

export interface ToolchainPin {
  /** mise tool spec, e.g. `ubi:rojo-rbx/rojo`. */
  spec: string;
  version: string;
}

export interface ToolchainModel {
  flavor: InitFlavor;
  tools: ToolchainPin[];
  configPath: string;
}

const ROJO_PIN: ToolchainPin = { spec: "ubi:rojo-rbx/rojo", version: "7.4.4" };
const WALLY_PIN: ToolchainPin = { spec: "ubi:UpliftGames/wally", version: "0.3.2" };

/** Build a deterministic, flavor-aware toolchain model. */
export function buildToolchainModel(flavor: InitFlavor): ToolchainModel {
  const tools: ToolchainPin[] = [ROJO_PIN];
  if (flavor === "luau-wally") {
    tools.push(WALLY_PIN);
  }
  return {
    flavor,
    tools,
    configPath: MISE_CONFIG_PATH,
  };
}

/** Render a deterministic `mise.toml` body. Contains no Aftman references. */
export function renderMiseToml(model: ToolchainModel): string {
  const lines: string[] = [
    "# Generated by RobloxUI CLI. Pinned via mise.",
    "[tools]",
  ];
  for (const tool of model.tools) {
    lines.push(`"${tool.spec}" = "${tool.version}"`);
  }
  lines.push("");
  return lines.join("\n");
}

export interface ToolchainPreviewFile {
  path: string;
  content: string;
}

export interface ToolchainPreview {
  id: string;
  confirmId: string;
  files: ToolchainPreviewFile[];
}

/** Build a reviewable preview of the files the toolchain step will write. */
export function buildToolchainPreview(model: ToolchainModel): ToolchainPreview {
  return {
    id: PREVIEW_ID,
    confirmId: CONFIRM_ID,
    files: [
      {
        path: model.configPath,
        content: renderMiseToml(model),
      },
    ],
  };
}

export interface AftmanMigrationPlan {
  /** True when a legacy `aftman.toml` is present on disk. */
  detected: boolean;
  /** Equivalent mise configuration the developer can adopt. */
  equivalentPreview: string;
  /** Always false — legacy files are never modified automatically (EC-07). */
  touched: boolean;
}

/**
 * Plan (but do not execute) migration from a legacy `aftman.toml`.
 * The legacy file is left byte-for-byte untouched (EC-07).
 */
export function planAftmanMigration(
  model: ToolchainModel,
  aftmanTomlExists: boolean
): AftmanMigrationPlan {
  return {
    detected: aftmanTomlExists,
    equivalentPreview: renderMiseToml(model),
    touched: false,
  };
}

export interface MissingToolchainReport {
  exitCode: number;
  message: string;
  retryCommand: string;
}

/** Actionable, nonzero guidance when mise is unavailable (EC-06). */
export function reportMissingMise(): MissingToolchainReport {
  return {
    exitCode: 1,
    message: "mise is required for pinned toolchain setup.",
    retryCommand: "mise install",
  };
}
